'use strict';
require('dotenv').config();
const mongoose = require('mongoose');
const User = require('./src/models/User');
const Product = require('./src/models/Product');
const Project = require('./src/models/Project');

const allProducts = [
  // ── 1. ELECTRICAL & ELECTRONICS ──────────────────────────────────────
  { name: 'Power Contactor 32A 3-Phase 415V', description: 'Heavy-duty 3-phase power contactor 32A for industrial motor control and switching. Suitable for MCC panels and motor starters.', shortDescription: '32A 3-phase power contactor for MCC panels', price: 1850, discountPrice: 1600, category: 'Electrical', subcategory: 'Electrical & Electronics', stock: 80, unit: 'piece', isFeatured: true, brand: 'Siemens/Equivalent', tags: ['contactor', 'motor control', 'mcc'], specifications: [{ key: 'Current', value: '32A' }, { key: 'Voltage', value: '415V AC' }, { key: 'Poles', value: '3' }], sku: 'ACS-ELE-001' },
  { name: 'Capacitor Bank 25 kVAR 440V', description: 'Power factor correction capacitor 25 kVAR for industrial installations. Improves power factor and reduces energy bills.', price: 4500, discountPrice: 3999, category: 'Electrical', subcategory: 'Electrical & Electronics', stock: 30, unit: 'piece', tags: ['capacitor', 'power factor'], specifications: [{ key: 'Rating', value: '25 kVAR' }, { key: 'Voltage', value: '440V' }], sku: 'ACS-ELE-002' },
  { name: 'Resistor Assorted Pack 1W (50 pcs)', description: 'Carbon film resistors 1W assorted values. For control circuits and instrumentation panels.', price: 350, discountPrice: 280, category: 'Electrical', subcategory: 'Electrical & Electronics', stock: 200, unit: 'pack', tags: ['resistor', 'electronics'], sku: 'ACS-ELE-003' },
  { name: 'IC LM741 Op-Amp Pack of 10', description: 'General purpose operational amplifier IC LM741. For instrumentation, signal conditioning and control circuits.', price: 120, category: 'Electrical', subcategory: 'Electrical & Electronics', stock: 500, unit: 'pack', tags: ['ic', 'op-amp', 'instrumentation'], sku: 'ACS-ELE-004' },
  { name: 'Solid State Relay SSR 40A DC-AC', description: 'Industrial grade solid state relay 40A DC to AC. No moving parts, silent operation, long life. For automation.', price: 950, discountPrice: 799, category: 'Electrical', subcategory: 'Electrical & Electronics', stock: 60, unit: 'piece', tags: ['ssr', 'relay', 'automation'], sku: 'ACS-ELE-005' },
  { name: 'Solenoid Coil Connector DIN 43650', description: 'DIN 43650 solenoid coil connector with LED indicator. For valves and actuators in industrial automation.', price: 280, category: 'Electrical', subcategory: 'Electrical & Electronics', stock: 150, unit: 'piece', tags: ['solenoid', 'connector', 'valve'], sku: 'ACS-ELE-006' },
  { name: 'LED Strip Light 5M Roll IP65 Waterproof', description: 'Waterproof LED strip 5050 SMD, 60 LEDs/meter, IP65 rated. For industrial and commercial lighting.', price: 850, discountPrice: 699, category: 'Electrical', subcategory: 'Electrical & Electronics', stock: 100, unit: 'roll', isFeatured: true, tags: ['led', 'strip light', 'ip65'], sku: 'ACS-ELE-007' },
  { name: 'Rechargeable Battery 12V 7Ah Sealed', description: 'Sealed rechargeable lead-acid battery 12V 7Ah for UPS systems, emergency lighting and backup power.', price: 1200, category: 'Electrical', subcategory: 'Electrical & Electronics', stock: 40, unit: 'piece', tags: ['battery', 'backup power', 'ups'], sku: 'ACS-ELE-008' },
  { name: 'MCC Panel 415V 100A Industrial', description: 'Motor Control Centre panel 415V 100A with MCCB, contactors and overload relays. Custom configurations available.', price: 85000, discountPrice: 78000, category: 'Electrical', subcategory: 'Electrical & Electronics', stock: 8, unit: 'piece', isFeatured: true, tags: ['mcc', 'panel', 'motor control'], specifications: [{ key: 'Voltage', value: '415V' }, { key: 'Current', value: '100A' }], sku: 'ACS-ELE-009' },
  { name: 'DG Set 15 kVA Silent Type Diesel', description: 'Silent diesel generator set 15 kVA for industrial backup power. Soundproof canopy, auto start panel included.', price: 185000, category: 'Electrical', subcategory: 'Electrical & Electronics', stock: 5, unit: 'set', isFeatured: true, tags: ['generator', 'dg set', 'backup power'], specifications: [{ key: 'Capacity', value: '15 kVA' }, { key: 'Fuel', value: 'Diesel' }], sku: 'ACS-ELE-010' },
  { name: 'Earth Enhancing Compound Curecon 5KG', description: 'Backfill compound for earthing systems. Reduces soil resistivity, increases electrode efficiency.', price: 1800, discountPrice: 1599, category: 'Electrical', subcategory: 'Electrical & Electronics', stock: 80, unit: 'pack', tags: ['earthing', 'grounding', 'curecon'], sku: 'ACS-ELE-011' },
  { name: 'Earthing GI Pipe 40mm x 3M Electrode', description: 'Galvanized iron earthing pipe 40mm × 3 meter for grounding systems in electrical installations.', price: 1200, discountPrice: 999, category: 'Electrical', subcategory: 'Electrical & Electronics', stock: 150, unit: 'piece', tags: ['earthing', 'gi pipe', 'grounding'], sku: 'ACS-ELE-012' },

  // ── 2. CABLES & CONNECTIVITY ──────────────────────────────────────────
  { name: 'XLPE Cable 3.5C x 95 SQMM Aluminium Underground', description: 'Aluminium conductor XLPE insulated armoured underground cable. For HT/LT power distribution in industrial plants.', price: 480, category: 'Cable', subcategory: 'Cables & Connectivity', stock: 2000, unit: 'meter', isFeatured: true, minOrderQty: 100, tags: ['xlpe', 'underground', 'aluminium', 'power cable'], specifications: [{ key: 'Conductor', value: 'Aluminium' }, { key: 'Cross Section', value: '95 sq mm' }, { key: 'Cores', value: '3.5C' }], sku: 'ACS-CAB-001' },
  { name: 'Control Cable 4C x 2.5 SQMM FRLS', description: 'Flame retardant low smoke PVC insulated control cable 4 core 2.5 sq mm. For instrument and control panel wiring.', price: 95, category: 'Cable', subcategory: 'Cables & Connectivity', stock: 5000, unit: 'meter', minOrderQty: 50, tags: ['control cable', 'frls', 'instrumentation'], sku: 'ACS-CAB-002' },
  { name: 'OFC Single Mode Fiber Cable 12 Core OS2', description: '12 core single mode OS2 optical fiber cable for high-speed data. Outdoor rated, suitable for industrial runs.', price: 85, discountPrice: 72, category: 'Cable', subcategory: 'Cables & Connectivity', stock: 3000, unit: 'meter', isFeatured: true, minOrderQty: 100, tags: ['ofc', 'fiber', 'single mode', 'os2'], sku: 'ACS-CAB-003' },
  { name: 'HDMI 2.0 Cable High Speed 4K 3 Meter', description: 'Premium HDMI 2.0 cable supporting 4K@60Hz. Braided nylon jacket for durability. For industrial displays.', price: 350, discountPrice: 299, category: 'Cable', subcategory: 'Cables & Connectivity', stock: 200, unit: 'piece', tags: ['hdmi', 'display', '4k'], sku: 'ACS-CAB-004' },
  { name: 'DisplayPort 1.4 Cable 8K (2 Meter)', description: 'DisplayPort 1.4 cable supporting 8K resolution. Unidirectional for monitors and industrial displays.', price: 450, discountPrice: 380, category: 'Cable', subcategory: 'Cables & Connectivity', stock: 100, unit: 'piece', tags: ['displayport', 'cable', '8k'], sku: 'ACS-CAB-005' },
  { name: 'Cat 6 UTP LAN Cable 305M Pull Box', description: 'Category 6 UTP Ethernet cable 305 meter box. Supports 10 Gbps at 250 MHz. For structured cabling.', price: 4200, discountPrice: 3800, category: 'Cable', subcategory: 'Cables & Connectivity', stock: 50, unit: 'box', isFeatured: true, tags: ['cat6', 'lan', 'ethernet', 'structured cabling'], sku: 'ACS-CAB-006' },
  { name: 'Cat 6 Patch Cord 0.5M Pack of 10', description: 'Cat6 patch cords 0.5 meter RJ45 both ends, pack of 10. For server racks and patch panels.', price: 650, category: 'Cable', subcategory: 'Cables & Connectivity', stock: 150, unit: 'pack', tags: ['patch cord', 'cat6', 'rj45'], sku: 'ACS-CAB-007' },
  { name: 'Cable Gland PG-11 Brass IP68 Pack of 25', description: 'Brass cable gland PG-11 for cable entry sealing in junction boxes and panels. IP68 rated.', price: 420, category: 'Cable', subcategory: 'Cables & Connectivity', stock: 500, unit: 'pack', tags: ['cable gland', 'brass', 'pg11', 'ip68'], sku: 'ACS-CAB-008' },
  { name: 'Aluminium Cable Lug 95 SQMM Pack of 10', description: 'Aluminium compression cable lugs for 95 sq mm cables. For terminations at bus bars and panels.', price: 380, category: 'Cable', subcategory: 'Cables & Connectivity', stock: 300, unit: 'pack', tags: ['cable lug', 'aluminium', 'termination'], sku: 'ACS-CAB-009' },
  { name: 'Nylon Cable Ties 300mm Heavy Duty Pack 100', description: 'Heavy duty nylon cable ties 300mm × 4.8mm. UV resistant. For cable management in industrial plants.', price: 180, category: 'Cable', subcategory: 'Cables & Connectivity', stock: 1000, unit: 'pack', tags: ['cable tie', 'nylon', 'uv resistant'], sku: 'ACS-CAB-010' },
  { name: 'OFC Dome Type Joint Closure 6 Core', description: 'Optical fiber cable joint closure dome type for 6 core splice. Waterproof, UV resistant.', price: 750, discountPrice: 620, category: 'Cable', subcategory: 'Cables & Connectivity', stock: 80, unit: 'piece', tags: ['ofc', 'joint closure', 'fiber'], sku: 'ACS-CAB-011' },
  { name: 'GI Perforated Cable Tray 300mm x 3M', description: 'Galvanized iron perforated cable tray 300mm wide × 3 meter length. 2mm thick powder coated.', price: 1350, discountPrice: 1150, category: 'Cable', subcategory: 'Cables & Connectivity', stock: 400, unit: 'piece', isFeatured: true, minOrderQty: 10, tags: ['cable tray', 'gi', 'perforated', '300mm'], sku: 'ACS-CAB-012' },
  { name: 'Instrumentation Cable 4P x 0.5 SQMM Shielded', description: 'Twisted pair shielded instrumentation cable 4 pair × 0.5 sq mm. For signal transmission in noisy environments.', price: 65, category: 'Cable', subcategory: 'Cables & Connectivity', stock: 3000, unit: 'meter', minOrderQty: 100, tags: ['instrumentation cable', 'shielded', 'twisted pair'], sku: 'ACS-CAB-013' },

  // ── 3. NETWORKING & COMMUNICATION ─────────────────────────────────────
  { name: 'IP NVR 16 Channel 4K H.265+', description: 'Network Video Recorder 16 channel supporting 4K resolution. H.265+ compression, supports up to 8TB HDD.', price: 18500, discountPrice: 16500, category: 'Networking', subcategory: 'Networking & Communication', stock: 20, unit: 'piece', isFeatured: true, tags: ['nvr', 'cctv', '4k', 'surveillance'], specifications: [{ key: 'Channels', value: '16' }, { key: 'Resolution', value: '4K 8MP' }, { key: 'Compression', value: 'H.265+' }], sku: 'ACS-NET-001' },
  { name: 'IP CCTV Dome Camera 5MP IR Night Vision', description: '5MP IP dome camera with IR 30m, IP67 weatherproof, 2.8mm wide angle lens. Indoor/outdoor use.', price: 3200, discountPrice: 2799, category: 'Networking', subcategory: 'Networking & Communication', stock: 60, unit: 'piece', isFeatured: true, tags: ['cctv', 'ip camera', 'dome', 'night vision'], sku: 'ACS-NET-002' },
  { name: 'Managed Gigabit Switch 8 Port Industrial', description: '8 port Gigabit managed switch with VLAN, QoS and SNMP support. Rack mountable, industrial grade.', price: 5500, discountPrice: 4800, category: 'Networking', subcategory: 'Networking & Communication', stock: 25, unit: 'piece', tags: ['switch', 'managed', 'gigabit'], sku: 'ACS-NET-003' },
  { name: 'RS485 to USB Converter Industrial FTDI', description: 'Industrial RS485 to USB converter with FTDI chip. 300bps–921.6Kbps. For SCADA and PLC communication.', price: 650, discountPrice: 550, category: 'Networking', subcategory: 'Networking & Communication', stock: 80, unit: 'piece', tags: ['rs485', 'usb', 'scada', 'plc'], sku: 'ACS-NET-004' },
  { name: 'USB & LAN Port Blocker with Key Pack of 10', description: 'USB and LAN port security locks with master key. Prevents unauthorized data transfer. IT security essential.', price: 1200, discountPrice: 999, category: 'Networking', subcategory: 'Networking & Communication', stock: 200, unit: 'pack', isFeatured: true, tags: ['usb blocker', 'lan blocker', 'security', 'port lock'], sku: 'ACS-NET-005' },
  { name: 'Gigabit Fiber Media Converter SFP', description: 'Single mode fiber to RJ45 Gigabit media converter with SFP slot. Converts copper Ethernet to fiber signal.', price: 2200, discountPrice: 1850, category: 'Networking', subcategory: 'Networking & Communication', stock: 40, unit: 'piece', tags: ['media converter', 'fiber', 'sfp', 'gigabit'], sku: 'ACS-NET-006' },
  { name: 'USB 3.0 Pen Drive 32GB (Pack of 5)', description: 'High speed USB 3.0 pen drive 32GB, read 100MB/s. For data transfer in industrial environments.', price: 1100, discountPrice: 899, category: 'Networking', subcategory: 'Networking & Communication', stock: 100, unit: 'pack', tags: ['pen drive', 'usb 3.0', 'storage'], sku: 'ACS-NET-007' },
  { name: 'ODU Outdoor Unit Enclosure Box IP66', description: 'Outdoor unit enclosure box IP66 rated for network equipment. UV resistant polycarbonate construction.', price: 3500, category: 'Networking', subcategory: 'Networking & Communication', stock: 30, unit: 'piece', tags: ['odu', 'outdoor enclosure', 'ip66'], sku: 'ACS-NET-008' },
  { name: 'Industrial PA Horn Speaker 20W IP66', description: 'Weatherproof horn speaker 20W, 100V line. IP66 rated for outdoor PA systems in industrial plants.', price: 2200, discountPrice: 1899, category: 'Networking', subcategory: 'Networking & Communication', stock: 30, unit: 'piece', tags: ['speaker', 'pa system', 'horn', 'ip66'], sku: 'ACS-NET-009' },

  // ── 4. SAFETY MATERIALS / PPE ─────────────────────────────────────────
  { name: 'Safety Helmet HDPE ISI Marked Yellow', description: 'HDPE safety helmet ISI certification IS:2925. Adjustable ratchet suspension, UV stabilized, vented design.', price: 350, discountPrice: 299, category: 'Safety', subcategory: 'Safety Materials / PPE', stock: 500, unit: 'piece', isFeatured: true, tags: ['helmet', 'ppe', 'isi', 'hdpe'], specifications: [{ key: 'Standard', value: 'IS:2925' }, { key: 'Material', value: 'HDPE' }], sku: 'ACS-SAF-001' },
  { name: 'Electrical Insulating Gloves 11kV Class 1', description: 'Rubber insulated electrical gloves Class 1 rated 11kV. For HT electrical work. AS/NZS 2225 compliant.', price: 2200, discountPrice: 1999, category: 'Safety', subcategory: 'Safety Materials / PPE', stock: 80, unit: 'pair', isFeatured: true, tags: ['gloves', 'insulated', '11kv', 'ht work'], specifications: [{ key: 'Voltage', value: '11kV' }, { key: 'Class', value: '1' }], sku: 'ACS-SAF-002' },
  { name: 'Safety Shoes Steel Toe S3 ISI Marked', description: 'Steel toe cap safety shoes S3 category with anti-slip sole, oil resistant, ankle support. ISI marked.', price: 1800, discountPrice: 1550, category: 'Safety', subcategory: 'Safety Materials / PPE', stock: 120, unit: 'pair', tags: ['safety shoes', 'steel toe', 's3'], sku: 'ACS-SAF-003' },
  { name: 'Full Body Safety Harness Double Lanyard Fall Arrest', description: 'Full body fall arrest safety harness with double shock-absorbing lanyard. EN 361 compliant. For height work.', price: 3500, discountPrice: 2999, category: 'Safety', subcategory: 'Safety Materials / PPE', stock: 60, unit: 'set', isFeatured: true, tags: ['harness', 'fall arrest', 'height work', 'lanyard'], sku: 'ACS-SAF-004' },
  { name: 'Safety Goggles Anti-Fog Clear Pack 10', description: 'Indirect vent safety goggles anti-fog clear lens. ANSI Z87.1. Chemical and impact resistant.', price: 850, category: 'Safety', subcategory: 'Safety Materials / PPE', stock: 200, unit: 'pack', tags: ['goggles', 'eye protection', 'anti-fog'], sku: 'ACS-SAF-005' },
  { name: 'Electrical Insulation Mat 1M x 1M 11kV 3mm', description: 'Rubber electrical insulation mat 1m × 1m 3mm thick rated 11kV. For switchrooms and panel areas.', price: 4500, discountPrice: 3999, category: 'Safety', subcategory: 'Safety Materials / PPE', stock: 40, unit: 'piece', tags: ['insulation mat', 'rubber mat', '11kv', 'switchroom'], sku: 'ACS-SAF-006' },
  { name: 'Arc Flash Protection Suit 8 Cal/cm2 NFPA 70E', description: 'Arc flash protection coverall 8 cal/cm² with hood, gloves and face shield. For HV electrical maintenance.', price: 18500, category: 'Safety', subcategory: 'Safety Materials / PPE', stock: 15, unit: 'set', isFeatured: true, tags: ['arc flash', 'hv safety', 'nfpa 70e'], specifications: [{ key: 'Rating', value: '8 cal/cm²' }, { key: 'Standard', value: 'NFPA 70E' }], sku: 'ACS-SAF-007' },
  { name: 'HV Earthing & Discharge Rod Set 33kV', description: 'Portable earthing and short-circuit device for 33kV systems. Ensures safe discharge before HV line maintenance.', price: 8500, category: 'Safety', subcategory: 'Safety Materials / PPE', stock: 20, unit: 'set', tags: ['discharge rod', 'earthing', '33kv', 'hv safety'], sku: 'ACS-SAF-008' },
  { name: 'N95 Respirator Dust Mask Box of 20', description: 'N95 particulate respirator with exhalation valve. NIOSH approved. For dusty industrial environments.', price: 480, discountPrice: 399, category: 'Safety', subcategory: 'Safety Materials / PPE', stock: 300, unit: 'box', tags: ['n95', 'mask', 'respirator', 'dust protection'], sku: 'ACS-SAF-009' },
  { name: 'Hi-Vis Safety Vest Reflective 3M Tape Orange', description: 'High visibility orange vest with 3M reflective tape. IS 15809 compliant. For construction sites and plants.', price: 280, discountPrice: 220, category: 'Safety', subcategory: 'Safety Materials / PPE', stock: 600, unit: 'piece', tags: ['safety vest', 'hi-vis', 'reflective', '3m'], sku: 'ACS-SAF-010' },

  // ── 5. MECHANICAL, PIPING & INDUSTRIAL TOOLS ─────────────────────────
  { name: 'SS 304 Ball Valve 2 Inch Flanged Full Bore', description: 'Stainless steel 304 ball valve 2 inch flanged. Full bore, 150lb rated. For industrial process piping.', price: 2800, discountPrice: 2399, category: 'Mechanical', subcategory: 'Mechanical, Piping & Industrial Tools', stock: 80, unit: 'piece', isFeatured: true, tags: ['ball valve', 'ss304', 'flanged'], sku: 'ACS-MEC-001' },
  { name: 'UPVC Pipe 110mm x 3M Schedule 40 Pressure', description: 'UPVC pressure pipe 110mm diameter × 3 meter. Schedule 40. For water supply and chemical piping.', price: 850, category: 'Mechanical', subcategory: 'Mechanical, Piping & Industrial Tools', stock: 300, unit: 'piece', minOrderQty: 10, tags: ['upvc', 'pipe', 'pressure pipe'], sku: 'ACS-MEC-002' },
  { name: 'PVC Conduit Pipe 25mm x 3M Heavy Duty Rigid', description: 'Heavy duty rigid PVC conduit 25mm × 3 meter. For electrical wiring protection in walls and underground.', price: 85, category: 'Mechanical', subcategory: 'Mechanical, Piping & Industrial Tools', stock: 1000, unit: 'piece', minOrderQty: 20, tags: ['conduit', 'pvc', 'electrical protection'], sku: 'ACS-MEC-003' },
  { name: 'MS Deck Plate 520mm x 2180mm x 3mm Thick', description: 'Mild steel deck plate 520×2180mm 3mm thick for industrial flooring, walkways and platforms.', price: 3500, category: 'Mechanical', subcategory: 'Mechanical, Piping & Industrial Tools', stock: 100, unit: 'piece', minOrderQty: 5, tags: ['deck plate', 'ms', 'platform', 'walkway'], sku: 'ACS-MEC-004' },
  { name: 'SS 304 U-Clamp 50mm Pack of 25', description: 'Stainless steel 304 U-clamp 50mm for pipe and cable fixing. Heavy duty, corrosion resistant.', price: 650, category: 'Mechanical', subcategory: 'Mechanical, Piping & Industrial Tools', stock: 400, unit: 'pack', tags: ['u-clamp', 'ss304', 'pipe clamp'], sku: 'ACS-MEC-005' },
  { name: 'Anti-Vibration Rubber Mount Set of 4', description: 'Anti-vibration rubber mounts for motor, pump and air washer mounting. Reduces noise and vibration.', price: 1200, discountPrice: 999, category: 'Mechanical', subcategory: 'Mechanical, Piping & Industrial Tools', stock: 60, unit: 'set', tags: ['vibration isolator', 'rubber mount', 'anti-vibration'], sku: 'ACS-MEC-006' },
  { name: 'Pneumatic Tubing & Fittings Kit 1/4 inch', description: 'Pneumatic tubing and push-fit fittings kit 1/4 inch. Elbows, T-junctions, unions and straight connectors included.', price: 1800, discountPrice: 1550, category: 'Mechanical', subcategory: 'Mechanical, Piping & Industrial Tools', stock: 50, unit: 'kit', tags: ['pneumatic', 'tubing', 'fittings'], sku: 'ACS-MEC-007' },
  { name: 'Heavy Duty Panel Cam Lock T-Handle Pack 10', description: 'Heavy duty cam lock with T-handle, quarter turn. For MCC and control panels. Comes with key.', price: 1400, discountPrice: 1199, category: 'Mechanical', subcategory: 'Mechanical, Piping & Industrial Tools', stock: 100, unit: 'pack', tags: ['panel lock', 'cam lock', 'mcc panel'], sku: 'ACS-MEC-008' },
  { name: 'SS Butt Hinges for MCC Panels Pack 10 Pairs', description: 'Heavy duty stainless steel butt hinges for MCC and control panels. For doors up to 30kg load.', price: 850, category: 'Mechanical', subcategory: 'Mechanical, Piping & Industrial Tools', stock: 120, unit: 'pack', tags: ['hinge', 'panel hinge', 'stainless steel'], sku: 'ACS-MEC-009' },
  { name: 'NBR O-Ring Assorted Kit 419 Pieces', description: 'NBR (nitrile rubber) O-ring assortment 419 pieces in 30 sizes. For hydraulic and pneumatic sealing.', price: 1200, discountPrice: 999, category: 'Mechanical', subcategory: 'Mechanical, Piping & Industrial Tools', stock: 60, unit: 'kit', tags: ['o-ring', 'nbr', 'hydraulic', 'seals'], sku: 'ACS-MEC-010' },
  { name: 'SS 304 Hex Bolt Nut M12 x 50mm Pack 25', description: 'Stainless steel 304 hex bolt and nut M12 × 50mm with washers. For structural and equipment mounting.', price: 580, category: 'Mechanical', subcategory: 'Mechanical, Piping & Industrial Tools', stock: 400, unit: 'pack', tags: ['bolt', 'nut', 'ss304', 'fasteners', 'm12'], sku: 'ACS-MEC-011' },

  // ── 6. TOOLS ──────────────────────────────────────────────────────────
  { name: 'Hydraulic Crimping Tool Set 10 Dies 16-400 SQMM', description: 'Professional hydraulic crimping tool set with 10 dies for 16–400 sq mm cable lugs and connectors.', price: 4200, discountPrice: 3699, category: 'Tools', subcategory: 'Mechanical, Piping & Industrial Tools', stock: 25, unit: 'set', isFeatured: true, tags: ['crimping tool', 'hydraulic', 'cable lug', 'termination'], sku: 'ACS-TOO-001' },
  { name: 'Chrome Vanadium Adjustable Wrench 8 & 12 inch Set', description: 'Chrome vanadium adjustable wrench set 8 inch and 12 inch pair. Precision machined jaw, rust resistant.', price: 850, discountPrice: 699, category: 'Tools', subcategory: 'Mechanical, Piping & Industrial Tools', stock: 80, unit: 'pair', tags: ['wrench', 'adjustable', 'chrome vanadium'], sku: 'ACS-TOO-002' },
  { name: 'Welding Electrodes E6013 3.2mm 5KG Pack', description: 'E6013 mild steel welding electrodes 3.2mm × 5kg. All position welding, smooth arc, easy slag removal.', price: 480, discountPrice: 420, category: 'Tools', subcategory: 'Mechanical, Piping & Industrial Tools', stock: 200, unit: 'pack', minOrderQty: 2, tags: ['welding electrode', 'e6013', 'ms welding'], sku: 'ACS-TOO-003' },
  { name: 'Angle Grinder Cutting Wheels 4 inch Pack 25', description: '4 inch × 1mm thin cutting wheels for angle grinder. Suitable for MS, SS and cast iron cutting.', price: 380, category: 'Tools', subcategory: 'Mechanical, Piping & Industrial Tools', stock: 300, unit: 'pack', tags: ['cutting wheel', 'grinder', 'abrasive', '4 inch'], sku: 'ACS-TOO-004' },
  { name: 'Aluminium Extension Ladder 20 Feet 150KG Rated', description: 'Aluminium extension ladder 20 feet (6m), 150kg rated. Non-slip rubber feet, safety lock. IS:1875.', price: 8500, discountPrice: 7499, category: 'Tools', subcategory: 'Mechanical, Piping & Industrial Tools', stock: 15, unit: 'piece', isFeatured: true, tags: ['ladder', 'extension', 'aluminium', '20 feet'], sku: 'ACS-TOO-005' },

  // ── 7. MULTIMEDIA & ACCESSORIES ───────────────────────────────────────
  { name: 'Industrial PA Amplifier 120W 100V Line', description: '120W PA amplifier for industrial intercom and announcement systems. 100V line output, rack mount.', price: 6500, category: 'Networking', subcategory: 'Multimedia & Accessories', stock: 15, unit: 'piece', tags: ['amplifier', 'pa system', '100v line'], sku: 'ACS-MUL-001' },
  { name: 'Reflective Safety Tape Yellow/Black 50mm x 45M', description: 'High visibility reflective tape yellow/black chevron, 50mm × 45 meters. For hazard marking in plants.', price: 650, discountPrice: 549, category: 'Safety', subcategory: 'Multimedia & Accessories', stock: 200, unit: 'roll', tags: ['reflective tape', 'hazard', 'safety marking'], sku: 'ACS-MUL-002' },
  { name: 'Aluminium Engraved Equipment Name Plate', description: 'Custom aluminium name plate with engraved text for equipment, panels and machinery. Min order 10 pcs.', price: 180, category: 'Mechanical', subcategory: 'Multimedia & Accessories', stock: 500, unit: 'piece', minOrderQty: 10, tags: ['name plate', 'aluminium', 'engraved', 'equipment label'], sku: 'ACS-MUL-003' },
  { name: 'Toughened Safety Glass 300x300mm 6mm Panel', description: 'Toughened safety glass 300×300mm 6mm thick for panel inspection windows and control room glazing.', price: 850, category: 'Mechanical', subcategory: 'Multimedia & Accessories', stock: 50, unit: 'piece', tags: ['toughened glass', 'panel window', 'inspection'], sku: 'ACS-MUL-004' },
  { name: 'Custom Vinyl Sign Board Safety Signage (per sqft)', description: 'Custom printed vinyl sign boards for safety signs, equipment labels and plant directional signage.', price: 150, category: 'Other', subcategory: 'Multimedia & Accessories', stock: 1000, unit: 'sq.ft', minOrderQty: 5, tags: ['sign board', 'vinyl', 'safety sign', 'custom'], sku: 'ACS-MUL-005' },
  { name: 'Office Stationery Monthly Supply Kit', description: 'Complete office stationery: A4 paper, pens, markers, staplers, files, registers, clips and more.', price: 1200, discountPrice: 999, category: 'Other', subcategory: 'Multimedia & Accessories', stock: 100, unit: 'kit', tags: ['stationery', 'office supplies', 'monthly'], sku: 'ACS-MUL-006' },

  // ── 8. CHEMICAL & MISCELLANEOUS ───────────────────────────────────────
  { name: 'Technical Grade Petroleum Jelly 1KG', description: 'Technical petroleum jelly for cable terminations, thread lubrication and anti-corrosion protection.', price: 380, discountPrice: 320, category: 'Other', subcategory: 'Chemical & Miscellaneous', stock: 200, unit: 'kg', tags: ['petroleum jelly', 'lubrication', 'anti-corrosion'], sku: 'ACS-CHM-001' },
  { name: 'RTV Silicon Compound Sealant 280ml High Temp', description: 'High temperature RTV silicone sealant 280ml. Waterproof, temperature resistant -60°C to +230°C. For panel gaskets.', price: 450, discountPrice: 380, category: 'Other', subcategory: 'Chemical & Miscellaneous', stock: 150, unit: 'piece', tags: ['silicone', 'sealant', 'rtv', 'waterproof'], sku: 'ACS-CHM-002' },
  { name: 'Aluminium Epoxy Putty Metal Repair 500gm', description: 'Aluminium-filled epoxy putty for metal repair, pipe leaks and surface restoration in industrial environments.', price: 620, discountPrice: 520, category: 'Other', subcategory: 'Chemical & Miscellaneous', stock: 100, unit: 'piece', tags: ['epoxy putty', 'metal repair', 'aluminum putty'], sku: 'ACS-CHM-003' },
  { name: 'IPA Industrial Cleaning Wipes Pack 100', description: 'Isopropyl alcohol pre-saturated industrial wipes. For cleaning electronics, panels and sensitive equipment.', price: 350, discountPrice: 299, category: 'Other', subcategory: 'Chemical & Miscellaneous', stock: 300, unit: 'pack', tags: ['ipa wipes', 'cleaning', 'electronics', 'ipa'], sku: 'ACS-CHM-004' },
  { name: 'White Cotton Wiping Rags Cloth Waste 5KG', description: 'White cotton wiping rags 5kg bundle. For machine cleaning, oil wiping and general industrial use.', price: 280, category: 'Other', subcategory: 'Chemical & Miscellaneous', stock: 500, unit: 'bundle', tags: ['cloth waste', 'wiping rags', 'cotton'], sku: 'ACS-CHM-005' },
  { name: 'Rodent Repellent Spray 3M Brand 500ml', description: '3M brand rodent repellent spray for cable trays, panels and equipment. Prevents rodent cable damage.', price: 1200, discountPrice: 999, category: 'Other', subcategory: 'Chemical & Miscellaneous', stock: 120, unit: 'piece', isFeatured: true, tags: ['rodent repellent', '3m', 'cable protection', 'pest control'], sku: 'ACS-CHM-006' },
  { name: 'LDPE Polythene Sheet 200 Micron 4M x 50M Roll', description: 'Heavy duty LDPE polythene sheet 200 micron 4m × 50m roll. For waterproofing, DPC and civil protection.', price: 3200, discountPrice: 2800, category: 'Civil', subcategory: 'Chemical & Miscellaneous', stock: 50, unit: 'roll', tags: ['polythene', 'ldpe', 'waterproofing', 'dpc'], sku: 'ACS-CHM-007' },
  { name: 'Compatible Printer Cartridge HP 802 Black', description: 'Compatible cartridge HP 802 black, 650 page yield. For HP Deskjet inkjet printers.', price: 280, discountPrice: 240, category: 'Other', subcategory: 'Chemical & Miscellaneous', stock: 200, unit: 'piece', tags: ['cartridge', 'printer', 'hp 802', 'ink'], sku: 'ACS-CHM-008' },

  // ── 9. CIVIL SUPPLIES ─────────────────────────────────────────────────
  { name: 'Stone Aggregate 20mm (Per Metric Ton)', description: 'Crushed stone aggregate 20mm size for concrete work, road base and civil construction. Royalty paid supply.', price: 1400, category: 'Civil', subcategory: 'Civil Supplies', stock: 10000, unit: 'MT', isFeatured: true, minOrderQty: 10, tags: ['aggregate', '20mm', 'stone', 'concrete'], sku: 'ACS-CIV-001' },
  { name: 'Stone Aggregate 10mm (Per Metric Ton)', description: 'Crushed stone aggregate 10mm for fine concrete, plaster and flooring works. Quality checked supply.', price: 1200, category: 'Civil', subcategory: 'Civil Supplies', stock: 10000, unit: 'MT', isFeatured: false, minOrderQty: 10, tags: ['aggregate', '10mm', 'stone', 'plaster'], sku: 'ACS-CIV-002' },
  { name: 'River Sand / Construction Sand (Per CFT)', description: 'River/M-sand for construction, plastering and concrete. Clean washed sand delivered to site.', price: 45, category: 'Civil', subcategory: 'Civil Supplies', stock: 100000, unit: 'CFT', minOrderQty: 100, tags: ['sand', 'river sand', 'construction sand'], sku: 'ACS-CIV-003' },
  { name: 'Filling Sand / Backfill Sand (Per CFT)', description: 'Filling grade sand for earth filling, trench backfilling and civil foundation work.', price: 30, category: 'Civil', subcategory: 'Civil Supplies', stock: 100000, unit: 'CFT', minOrderQty: 100, tags: ['filling sand', 'backfill', 'earthwork'], sku: 'ACS-CIV-004' },
  { name: 'Burnt Lime Grits / Chuna (Per 50KG Bag)', description: 'Burnt lime (calcium oxide) grits for whitewashing, mortar and civil finishing works. 50kg bags.', price: 380, category: 'Civil', subcategory: 'Civil Supplies', stock: 500, unit: 'bag', minOrderQty: 5, tags: ['lime', 'burnt lime', 'whitewash', 'mortar'], sku: 'ACS-CIV-005' },
];

// ─── PROJECTS ──────────────────────────────────────────────────────────────────
const allProjects = [
  { title: 'Solar PV Power Plant — PPGCL 3×660MW', client: 'Prayagraj Power Generation Company Ltd', location: 'Bara, Prayagraj, UP', category: 'solar', description: 'Grid Connected Solar PV Power Plant including Civil, Structural and Electrical Works at PPGCL. Total order value ₹2.24 Crores.', highlights: ['Solar PV Design & Engineering', 'Module Mounting Structure', 'Grid Synchronization & Commissioning', 'DC & AC Cable Laying'], status: 'completed', isFeatured: true, purchaseOrderRef: '7000000119' },
  { title: 'Thermax FGD Electrical & I&C Works PPGCL', client: 'Thermax Limited (PGD Division)', location: 'Bara, Prayagraj, UP', category: 'electrical', description: 'Electrical & Instrumentation Works at FGD Project including transformer erection, panel installation, cable laying, earthing and comprehensive E&I commissioning. Total PO ₹2.5 Crores.', highlights: ['400kV Transformer Erection', 'LV/HV Switchboard', 'Cable Tray & Laying', 'Earthing & Lightning', 'CCTV, PA & FDA Systems'], status: 'ongoing', isFeatured: true, purchaseOrderRef: 'PO-203662' },
  { title: 'Toshiba 400kV Transformer & SCADA — PPGCL', client: 'Toshiba Transmission & Distribution (India) Pvt Ltd', location: 'Bara, Prayagraj, UP', category: 'electrical', description: 'Electrical installation, testing & commissioning of 400kV transformer systems, 11kV/33kV switchgear panels and SCADA integration at PPGCL 3×660MW. PO value ₹1.21 Crore.', highlights: ['400kV Transformer Commissioning', '33kV Switchgear', 'SCADA Integration', 'HV Cable Laying'], status: 'ongoing', isFeatured: true, purchaseOrderRef: 'PO-4456' },
  { title: 'Air Canon & Cable Tray Reorientation — Adani', client: 'Adani Infrastructure Management', location: 'Godda, Jharkhand', category: 'mechanical', description: 'Air Canon Relocation and Cable Tray Reorientation works in Boiler Area Unit#1 AOH for 2×800 MW Thermal Power Plant.', highlights: ['Air Canon Relocation', 'Boiler Area Works', '2×800 MW Plant', 'Cable Tray Reorientation'], status: 'ongoing', isFeatured: true, purchaseOrderRef: 'SO 5700391749' },
  { title: 'Scaffolding OLA — Tata Power IEL Jajpur', client: 'The Tata Power Co. Ltd. (IEL, Kalinganagar)', location: 'Kalinganagar, Jajpur, Odisha', category: 'mechanical', description: 'Annual rate contract for scaffolding services for day-to-day activities and shutdown at Industrial Energy Ltd inside Tata Steel CPP1. Contract value ₹36 Lakhs.', highlights: ['Daily Scaffolding', 'Shutdown Support', 'CPP1 Kalinganagar', '₹36 Lakh OLA'], status: 'ongoing', isFeatured: true, purchaseOrderRef: 'OA-9200031574' },
  { title: 'SAUBHAGYA YOJNA Transmission Line — Tata', client: 'TATA Projects Ltd (via Vishal Enterprises)', location: 'Banda, Uttar Pradesh', category: 'electrical', description: '11kV/440V electrical transmission line with PCC pole erection and DTR structure under PM SAUBHAGYA YOJNA rural electrification scheme.', highlights: ['PCC Pole Erection', '11kV/440V Cabling', 'DTR Structure', 'Rural Electrification'], status: 'completed', isFeatured: false },
  { title: 'Road Construction 1.5 KM — PWD Prayagraj', client: 'PWD Prayagraj (via M/s Uma Contractor)', location: 'Prayagraj, UP', category: 'civil', description: 'Construction of 1.5 km road from Mandar Mod Masjid under PWD Prayagraj. Base course to bituminous pavement, Contract ₹9.93 Crores.', highlights: ['1.5 KM Road', 'Bituminous Pavement', 'PWD Specification'], status: 'completed', isFeatured: false },
  { title: 'Overhead Tank Construction — Pratapgarh', client: 'Power Mech Projects Limited', location: 'Pratapgarh, UP', category: 'civil', description: 'Construction of 14m high RCC Overhead Tanks at 4 sites in Pratapgarh including pump house, boundaries and foundation.', highlights: ['14m High RCC Tank', 'Pump House', '4 Sites'], status: 'ongoing', isFeatured: false },
  { title: 'MASCOT Electromech 33kV Cable & RMU Works', client: 'MASCOT Electromech Pvt. Ltd.', location: 'Bara, Prayagraj, UP', category: 'electrical', description: 'Testing, commissioning and installation of RMU, ACDB, Feeder Pillars, Transformers, 33kV underground cable laying and terminations.', highlights: ['33kV Underground Cable', 'RMU Installation', 'Transformer Commissioning'], status: 'completed', isFeatured: false },
  { title: 'PPGCL 50KT Silo C&I — Power Mech', client: 'Power Mech Projects Limited', location: 'Bara, Prayagraj, UP', category: 'electrical', description: 'Electrical and C&I works of 50K Silo at 3×660MW PPGCL including OFC cable laying, FDAS installation and RTD installation.', highlights: ['OFC Cable Laying', 'FDAS System', 'RTD Installation'], status: 'completed', isFeatured: false },
  { title: 'Storm Water Drain — FGD Thermax PPGCL', client: 'Thermax Limited', location: 'Bara, Prayagraj, UP', category: 'civil', description: 'Storm Water Drain RCC construction at 3×660MW FGD Project PPGCL. Includes excavation, concrete and backfilling.', highlights: ['RCC Drain Construction', 'FGD Project Site'], status: 'completed', isFeatured: false },
  { title: 'Private House 9000 sqft Fully Furnished', client: 'Private Client', location: 'Prayagraj, UP', category: 'civil', description: 'Construction of 9000 sq ft fully finished private house and 3500 sq ft superstructure for individual clients.', highlights: ['9000 sqft Finished', '3500 sqft Superstructure', 'Residential'], status: 'completed', isFeatured: false },
];

// ─── SEED ──────────────────────────────────────────────────────────────────────
const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('✅ MongoDB Connected\n');

    await Promise.all([User.deleteMany({}), Product.deleteMany({}), Project.deleteMany({})]);
    console.log('🗑️  Cleared existing data\n');
try {
  await Product.collection.dropIndex('slug_1');
  console.log('slug_1 index dropped');
} catch (error) {
  if (error.message.includes('ns not found') || error.message.includes('index not found')) {
    console.log('No old slug_1 index found, continuing...');
  } else {
    throw error;
  }
}
    console.log('slug_1 index dropped');
    // Admin
    const admin = await User.create({
      name: 'Aditri Admin',
      email: process.env.ADMIN_EMAIL || 'admin@aditri.com',
      password: process.env.ADMIN_PASSWORD || 'Admin@123#Secure',
      role: 'admin',
      isActive: true,
    });
    console.log(`✅ Admin created: ${admin.email}`);


    // Products
    const products = await Product.insertMany(allProducts);
    console.log(`\n✅ ${products.length} products seeded\n`);

    const catCount = {};
    const subCount = {};
    products.forEach(p => {
      catCount[p.category] = (catCount[p.category] || 0) + 1;
      if (p.subcategory) subCount[p.subcategory] = (subCount[p.subcategory] || 0) + 1;
    });

    console.log('  📦 By Category:');
    Object.entries(catCount).forEach(([c, n]) => console.log(`     ${c}: ${n}`));
    console.log('\n  🏷️  By Sub-Category:');
    Object.entries(subCount).forEach(([s, n]) => console.log(`     ${s}: ${n}`));

    // Projects
    const proj = await Project.insertMany(allProjects);
    console.log(`\n✅ ${proj.length} projects seeded`);

    console.log('\n══════════════════════════════════════════════');
    console.log('🎉  Seeding complete!');
    console.log('══════════════════════════════════════════════');
    console.log(`  Admin : ${process.env.ADMIN_EMAIL || 'admin@aditri.com'}`);
    console.log(`  Pass  : ${process.env.ADMIN_PASSWORD || 'Admin@123#Secure'}`);
    console.log(`  Items : ${products.length} products | ${proj.length} projects`);
    console.log('══════════════════════════════════════════════\n');
    process.exit(0);
  } catch (err) {
    console.log(process.env.MONGO_URI);
    console.error('❌ Seed failed:', err.message);
    if (err.writeErrors) err.writeErrors.slice(0, 5).forEach(e => console.error(' -', e.errmsg));
    process.exit(1);
  }
};

seed();
